// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AnkiDbContext))]
    [Migration("20250901140641_AddTable_Users")]
    partial class AddTable_Users
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Infrastructure.Data.Model.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeaningId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NativeSentenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetSentenceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MeaningId");

                    b.HasIndex("NativeSentenceId");

                    b.HasIndex("TargetSentenceId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Infrastructure.Data.Model.Meaning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Meanings");
                });

            modelBuilder.Entity("Infrastructure.Data.Model.Sentence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MeaningId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Meanings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Meanings");

                    b.ToTable("Sentences");
                });

            modelBuilder.Entity("Infrastructure.Data.Model.Tag", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Infrastructure.Data.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Exp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Infrastructure.Data.Model.UserCardState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EaseFactor")
                        .HasColumnType("REAL");

                    b.Property<int>("Interval")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastReviewed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextReview")
                        .HasColumnType("TEXT");

                    b.Property<int>("Repetitions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("UserCardStates");
                });

            modelBuilder.Entity("MeaningTag", b =>
                {
                    b.Property<int>("MeaningId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .HasColumnType("TEXT");

                    b.HasKey("MeaningId", "TagName");

                    b.HasIndex("TagName");

                    b.ToTable("MeaningTags", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Model.Card", b =>
                {
                    b.HasOne("Infrastructure.Data.Model.Meaning", "Meaning")
                        .WithMany("Cards")
                        .HasForeignKey("MeaningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Model.Sentence", "NativeSentence")
                        .WithMany()
                        .HasForeignKey("NativeSentenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Model.Sentence", "TargetSentence")
                        .WithMany()
                        .HasForeignKey("TargetSentenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meaning");

                    b.Navigation("NativeSentence");

                    b.Navigation("TargetSentence");
                });

            modelBuilder.Entity("Infrastructure.Data.Model.Sentence", b =>
                {
                    b.HasOne("Infrastructure.Data.Model.Meaning", "Meaning")
                        .WithMany("Sentences")
                        .HasForeignKey("Meanings");

                    b.Navigation("Meaning");
                });

            modelBuilder.Entity("Infrastructure.Data.Model.UserCardState", b =>
                {
                    b.HasOne("Infrastructure.Data.Model.Card", null)
                        .WithOne("UserCardState")
                        .HasForeignKey("Infrastructure.Data.Model.UserCardState", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeaningTag", b =>
                {
                    b.HasOne("Infrastructure.Data.Model.Meaning", null)
                        .WithMany()
                        .HasForeignKey("MeaningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Model.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Data.Model.Card", b =>
                {
                    b.Navigation("UserCardState");
                });

            modelBuilder.Entity("Infrastructure.Data.Model.Meaning", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Sentences");
                });
#pragma warning restore 612, 618
        }
    }
}
