// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AnkiDbContext))]
    partial class AnkiAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Infrastructure.Data.Model.CardTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeaningId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NativeSentenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetSentenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserCardStateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MeaningId");

                    b.HasIndex("NativeSentenceId");

                    b.HasIndex("TargetSentenceId");

                    b.HasIndex("UserCardStateId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("Infrastructure.Data.Model.CurriculumSectionTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurriculumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropertySpecificationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredExp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CurriculumSections");
                });

            modelBuilder.Entity("Infrastructure.Data.Model.CurriculumTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Curricula");
                });

            modelBuilder.Entity("Infrastructure.Data.Model.MeaningTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Meanings");
                });

            modelBuilder.Entity("Infrastructure.Data.Model.SentenceTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MeaningId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Meanings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Meanings");

                    b.ToTable("Sentences");
                });

            modelBuilder.Entity("Infrastructure.Data.Model.TagTable", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Infrastructure.Data.Model.UserCardStateTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EaseFactor")
                        .HasColumnType("REAL");

                    b.Property<int>("Interval")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastReviewed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextReview")
                        .HasColumnType("TEXT");

                    b.Property<int>("Repetitions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserCardStates");
                });

            modelBuilder.Entity("Infrastructure.Data.Model.UserTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Exp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MeaningTag", b =>
                {
                    b.Property<int>("MeaningId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagName")
                        .HasColumnType("TEXT");

                    b.HasKey("MeaningId", "TagName");

                    b.HasIndex("TagName");

                    b.ToTable("MeaningTags", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Model.CardTable", b =>
                {
                    b.HasOne("Infrastructure.Data.Model.MeaningTable", "Meaning")
                        .WithMany("Cards")
                        .HasForeignKey("MeaningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Model.SentenceTable", "NativeSentence")
                        .WithMany()
                        .HasForeignKey("NativeSentenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Model.SentenceTable", "TargetSentence")
                        .WithMany()
                        .HasForeignKey("TargetSentenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Model.UserCardStateTable", "UserCardState")
                        .WithMany()
                        .HasForeignKey("UserCardStateId");

                    b.Navigation("Meaning");

                    b.Navigation("NativeSentence");

                    b.Navigation("TargetSentence");

                    b.Navigation("UserCardState");
                });

            modelBuilder.Entity("Infrastructure.Data.Model.SentenceTable", b =>
                {
                    b.HasOne("Infrastructure.Data.Model.MeaningTable", "Meaning")
                        .WithMany("Sentences")
                        .HasForeignKey("Meanings");

                    b.Navigation("Meaning");
                });

            modelBuilder.Entity("MeaningTag", b =>
                {
                    b.HasOne("Infrastructure.Data.Model.MeaningTable", null)
                        .WithMany()
                        .HasForeignKey("MeaningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Model.TagTable", null)
                        .WithMany()
                        .HasForeignKey("TagName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Data.Model.MeaningTable", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Sentences");
                });
#pragma warning restore 612, 618
        }
    }
}
